### ISSUE TITLE
[bug] Steamcmd Segfaults and fails to launch server.

### ISSUE THREAD

**Issue by MaverickTN** [powareverb/stationeers-dedserver-docker#1]
**Host OS:** _Ubuntu 23.04_
**Host Architecture:** _x86_64_
**Docker Version:**  _24.0.5_
**Containerd Version:** _1.6.22_
**Hardware:** _Dell PowerEdge R620_
**CPUs:** _2_
**CPU Cores:** _20 Cores/40 Threads_
**Memory Amount:** _128GB_
**Launch Method:** _Docker Compose_

**docker-compose.yml**
```

version: '3'
services:
  stationeers:
    image: powareverb/stationeers-dedserver:latest
    cap_add:
      - NET_ADMIN
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
    environment:
      - TZ=America/Los_Angeles
      - SERVERNAME="My-Server"
      - SERVERPASSWORD="Password"
      - PLANETOID="mars"
      - SAVENAME="server"
      - TUMXDIRECT="true"
      - VERSION_BRANCH="public"
    volumes:
      - /opt/Docker/Stationeers:/home/steam/stationeers-server-dedicated
    restart:
       always

```
**Problem Description:** steamcmd updates and downloads the server app and segfaults after verifying or completing the download with the error "`/home/steam/steamcmd/steamcmd.sh: line 39:    13 Segmentation fault      (core dumped) $DEBUGGER "$STEAMEXE" "$@"`" I have auto restart enabled. It just continues the same process over and over.

**Logfile Included:** _Yes - Attached txt file._
[Stationeer Docker Log.txt](https://github.com/powareverb/stationeers-dedserver-docker/files/12328810/Stationeer.Docker.Log.txt)
